name: GitHub Moroccan active users
on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Fetch users
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - uses: gayanvoice/top-github-users-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
