name: Rank GitHub Moroccan active users by stars
on:
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:
jobs:
  stargazer:
    name: Stargazing users
    runs-on: ubuntu-22.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      contents: write
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}

      - uses: maximousblk/setup-deno@v2
      - run: deno run --allow-env --allow-net --allow-write --allow-read scripts/stargazer.ts
        env:
          TOKEN: ${{ secrets.API_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update morocco-shiny.json"
          add_options: "-A"
